apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: myapp
    image: busybox
    command: ['sh', '-c', 'echo Hello K8S! && sleep 600']
    resources:
      requests:
        memory: 64Mi
        cpu: 250m
      limits:
        memory: 128Mi
        cpu: 500m

