apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
  - name: secretcont
    image: busybox
    command: ['sh', '-c', 'echo Hello Kube! ${SECRET} && sleep 600']
    env:
    - name: SECRET
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: myKey


